[project]
name = "playnasty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "jupyterlab>=4.3.0",
    "notebook>=7.0.7",
    "numpy>=2.1.2",
]
